POST http://localhost:9000/api/article/dislikeArticle/639435ed31cccc10d3c7b67f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkzMWNmNmFlY2ZhMjg1YWRiMjdmYmEiLCJ1c2VyVHlwZSI6InN1cHBvcnRhZ2VudCIsImVtYWlsIjoic3VwcG9ydGFnZW50MUBzdXBwb3J0YWdlbnRzLmNvbSIsImlhdCI6MTY3MDY3MTc1NiwiZXhwIjoxNjcwNjc1MzU2fQ.f0EaRPjcBNQEXD929PmkGczv5thDByjX8ercPz6CN0U