POST http://localhost:9000/api/ticket/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhMzY5NmViOWRjZGViYTEwNjM5OWEiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjcwNjk2ODQ2LCJleHAiOjE2NzA3MDA0NDZ9.AYRHv6f1PiVWALgCXN4PdGQZwKx-0ejT-bkRx2CWw6g

{
    "title": "Ticket Slack test",
    "description": "test"
}