POST http://localhost:9000/api/ticket/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhMzY5NmViOWRjZGViYTEwNjM5OWEiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjcwMDAyMzQ0LCJleHAiOjE2NzAwMDU5NDR9.QixXUrympGmrvM3eMYIV1kzH3_Zmvi3Et0C1wsTxXVM

{
    "title": "Test Ticket",
    "description": "Test Ticket Description"
}