POST http://localhost:9000/api/article/addComment/639435ed31cccc10d3c7b67f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkzMWNmNmFlY2ZhMjg1YWRiMjdmYmEiLCJ1c2VyVHlwZSI6InN1cHBvcnRhZ2VudCIsImVtYWlsIjoic3VwcG9ydGFnZW50MUBzdXBwb3J0YWdlbnRzLmNvbSIsImlhdCI6MTY3MDY2NDI2OSwiZXhwIjoxNjcwNjY3ODY5fQ.ewqVNvkJtPA-E5F1HxVXRbLxp5MBnh6PnFRjZCTNBk4

{
    "Comment": "This is a comment 1"
}
