DELETE http://localhost:9000/api/article/deleteArticle/639435f231cccc10d3c7b682 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkzMWNmNmFlY2ZhMjg1YWRiMjdmYmEiLCJ1c2VyVHlwZSI6InN1cHBvcnRhZ2VudCIsImVtYWlsIjoic3VwcG9ydGFnZW50MUBzdXBwb3J0YWdlbnRzLmNvbSIsImlhdCI6MTY3MDY2MjkyMiwiZXhwIjoxNjcwNjY2NTIyfQ.OdJkv3sFnmya-6x1-KStKJf6rWtNR_ACZe8vzlVwb7I