DELETE http://localhost:9000/api/article/deleteComment/639435ed31cccc10d3c7b67f/639453a401f706feb7a579ee HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkzMWNmNmFlY2ZhMjg1YWRiMjdmYmEiLCJ1c2VyVHlwZSI6InN1cHBvcnRhZ2VudCIsImVtYWlsIjoic3VwcG9ydGFnZW50MUBzdXBwb3J0YWdlbnRzLmNvbSIsImlhdCI6MTY3MDY3MDk1NCwiZXhwIjoxNjcwNjc0NTU0fQ.iaBjZOZaDX3Ncv6BufkhRqN2yETKbTCMGW76MFcM0lM