DELETE http://localhost:9000/api/ticket/attachment/638a7378125230a84a0561b8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhMzY5NmViOWRjZGViYTEwNjM5OWEiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjcwMTgxODA3LCJleHAiOjE2NzAxODU0MDd9.5rHOU7oAda5fBBEF7Gkjby_M0haNM4HMqZ8FpFuf0Ig