DELETE http://localhost:9000/api/notifications/63970839b01518f08435a4d1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzkzMWNmNmFlY2ZhMjg1YWRiMjdmYmEiLCJ1c2VyVHlwZSI6InN1cHBvcnRhZ2VudCIsImVtYWlsIjoic3VwcG9ydGFnZW50MUBzdXBwb3J0YWdlbnRzLmNvbSIsImlhdCI6MTY3MDg0MjI1NCwiZXhwIjoxNjcwODQ1ODU0fQ.saEvAOSctd9kISiZEM2UbsKBSlYaCPv1C2Iv0uwTukQ
