GET http://localhost:9000/api/ticket/638a370b7baec695c0995182/attachments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhMzY5NmViOWRjZGViYTEwNjM5OWEiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjcwMTQ5OTM5LCJleHAiOjE2NzAxNTM1Mzl9.y6xTQmKV2_5LNpbfUXW9okwgss67tuc_J6ZBg5Ql2v4