GET http://localhost:9000/api/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzhhMzY5NmViOWRjZGViYTEwNjM5OWEiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjcwMDE3OTgxLCJleHAiOjE2NzAwMjE1ODF9.DkZ1NQRSJAF0diMvFWfSCIEtQgVcHbwrnrCptd4B7SU
