POST http://localhost:9000/api/user/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzg0ZTczMzhkMzAwMDIwNWZjMTRmOTkiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZW1haWwiOiJtYWhtb3VkZGRAdXNlcnMuY29tIiwiaWF0IjoxNjY5OTk4NDk5LCJleHAiOjE2NzAwMDIwOTl9.56K2AqEWjN7eRUQFW7QBFMCpQaK3A9tx3CPg4YwHSKM

{
  "userId": "638229f9711dffa5170c5154",
  "email": "tost1@users.com",
  "name": "Hi"
}